### ISSUE TITLE
Statefulness and cluster syncing issues

### ISSUE THREAD

**Issue by Dlahacz** [manticoresoftware/manticoresearch-helm#100] opened 2024-10-25 11:44 UTC
Hi,

We have multiple issues related to the cluster syncing status. I think all of them can be solved with a startup probe that marks the pod as running only after cluster_node_state is synced.

### Issue Examples
**Adding a New Worker** 
Syncing data to a new node takes a few minutes, but the load balancer starts serving queries to the new worker before all tables are synced. (I'm not sure if this one can be solved without changes in observer.php)

**Updating values.yaml** (Variables Related to Worker STS, Searchd Configuration, Resources, and Limits)

We have, for example, 3 workers.
The STS definition changes.
Kubernetes starts with worker-3; the pod is shut down.
A new worker-3 pod starts up, and worker-3 begins syncing with worker-2.
Since Searchd is running, Kubernetes thinks worker-3 is up and proceeds to restart worker-2.
Because worker-3 is not yet fully synced and worker-2 has restarted, worker-3's state is now destroyed.
The same happens for worker-2. When worker-1 restarts, there is no primary instance left, leaving the entire cluster in a broken state.

**Kubernetes Node Rotation** 
When, for example, I update Kubernetes nodes to a new version or change their instance types, a similar situation to the previous one can occur.

### Proposed Solution
Add a startup probe.
```if /usr/bin/mysql -e "show status;" | grep cluster_node_state | grep -q synced ; then exit 0; else exit 1; fi```

**Comment by Dlahacz** [comment] 2024-10-25 12:05
We would be happy to do the work, create a pull request, and test it in production etc. We just want to know your opinion on the solution beforehand, so our time isn't wasted.

**Comment by sanikolaev** [comment] 2024-10-28 09:07
Thanks for the issue @Dlahacz 
@djklim87 pls look into this.

**Comment by djklim87** [comment] 2024-11-13 10:59
Be aware that replication within Manticore uses worker hosts, such as `helm-manticoresearch-worker-1`. This host isn’t available until the `startupProbe` is completed. As a result, your code may encounter a race condition where replication cannot finish because the `startupProbe` hasn’t completed, and the probe itself cannot complete due to the pending replication process.

**Comment by djklim87** [comment] 2024-11-30 17:26
I’m not entirely sure about `observer.php`, as this script only updates the balancer. However, you have a valid point, and it could potentially be implemented through the replication scripts.

**Comment by sanikolaev** [comment] 2024-12-02 07:57
We are considering other ways to address issues like this:
- Implementing read/write load balancing directly through Kubernetes (without using distributed tables).
- Adding a special `/readiness` endpoint, which Kubernetes can use to stop sending traffic to a pod if its tables are out of sync.

**Comment by djklim87** [comment] 2024-12-02 13:59
@Dlahacz, could you provide an approximate amount of data stored in your instances? If possible, sharing a dump would be even better. This would allow me to reproduce the issue much faster and develop the most effective solution.

**Comment by djklim87** [comment] 2024-12-03 20:34
Fixed in https://github.com/manticoresoftware/manticoresearch-helm/releases/tag/manticoresearch-6.3.62

**Closed by djklim87** 2024-12-03 20:34 UTC

**Comment by sanikolaev** [comment] 2024-12-05 09:49
@Dlahacz can you please confirm it doesn't fail with the same symptoms as previously for you anymore?

**Comment by Dlahacz** [comment] 2024-12-06 13:22
Hi,
I’ve reviewed the PR and believe it will address all our current issues. (I wasn’t aware of the `publishNotReadyAddresses` svc option—great solution!) We plan to test it in production next week. Thanks so much!

**Comment by Dlahacz** [comment] 2024-12-06 13:34
> * Implementing read/write load balancing directly through Kubernetes (without using distributed tables).

Actualy, we are currently routing "read" traffic directly to workers via the workers service. This change was necessary because the load balancer was generating excessive internal (cross-AZ) traffic, which resulted in an additional $1,500 on our last AWS bill 🙈. Since we’re not using any logical sharding, an application load balancer doesn’t seem necessary at this point. (We’re still running a load balancer instance to manage disk chunk optimization.)

**Comment by Dlahacz** [comment] 2025-02-13 11:21
Fyi: Replication now works like a charm. Thanks
